select DATE_FORMAT(c.SALES_DATE,'%Y-%m-%d') SALES_DATE,c.PRODUCT_ID,c.USER_ID,c.SALES_AMOUNT
from (select SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
     from ONLINE_SALE a
      where DATE_FORMAT(SALES_DATE,'%Y%m') = '202203'
      UNION ALL
     select SALES_DATE,PRODUCT_ID,NULL as USER_ID,SALES_AMOUNT
     from OFFLINE_SALE b
     where DATE_FORMAT(SALES_DATE,'%Y%m') = '202203'
     ) c
order by c.SALES_DATE asc,c.PRODUCT_ID asc,c.USER_ID asc