SELECT B.CATEGORY , B.MAX_PRICE , A.PRODUCT_NAME
FROM FOOD_PRODUCT as A
join 
(SELECT CATEGORY , MAX(PRICE) AS "MAX_PRICE" FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) AS B 
on A.PRICE = B.MAX_PRICE
and A.CATEGORY = B.CATEGORY
order by B.MAX_PRICE desc